### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by Channappa94**
Completed contacted

### CODE REVIEW

**Review by pandurangsyt — CHANGES_REQUESTED** [review]
For this assignment, please change logic to show the data if it already exist. If no data then only name and number should be empty when app is opened.

**Review by pandurangsyt — CHANGES_REQUESTED** [review]
For this assignment, please change logic to show the data if it already exist. If no data then only name and number should be empty when app is opened.

**Comment by Channappa94** [comment]
> For this assignment, please change logic to show the data if it already exist. If no data then only name and number should be empty when app is opened.

**Comment by Channappa94** [comment]
Yes sir, I will make changes soon as possible

**Pull request closed without merging**
